export const copy = {
  app: { title: "Budget", description: "Budget mensile per coppia" },
  auth: {
    loginTitle: "Accedi",
    signupTitle: "Crea account",
    email: "Email",
    password: "Password",
    displayName: "Nome",
    cycleStartDay: "Giorno di inizio del ciclo",
    cycleStartDayHelp: "Il giorno del mese in cui ricevi lo stipendio (1–31).",
    submitLogin: "Accedi",
    submitSignup: "Crea account",
    haveAccount: "Hai già un account?",
    noAccount: "Non hai un account?",
    goLogin: "Accedi",
    goSignup: "Registrati",
    errorGeneric: "Si è verificato un errore. Riprova.",
  },
  header: { settings: "Impostazioni", logout: "Esci", cycle: "Ciclo" },
  fab: { addExpense: "Aggiungi spesa" },
  dashboard: {
    salary: "Stipendio",
    spent: "Speso",
    remaining: "Rimanente",
    percentSalary: "% stipendio",
    onBudget: (total: string) => `su ${total}`,
    consumed: (pct: string) => `${pct} del budget`,
    pacingTitle: "Andamento ciclo",
    pacingUnder: "Sotto pace ✓",
    pacingOver: "Oltre pace ⚠",
    pacingExpense: "Spesa",
    pacingTime: "Tempo",
    categoriesHeading: "Categorie",
    fixedBadge: "fisso",
    noCategories: "Nessuna categoria.",
    addOne: "Aggiungine una",
    noTransactions: "Nessuna transazione.",
  },
  expense: {
    newTitle: "Nuova spesa",
    amount: "Importo",
    category: "Categoria",
    date: "Data",
    note: "Nota",
    submit: "Salva",
    cancel: "Annulla",
    noCategory: "Nessuna categoria — creane una prima",
  },
  categories: {
    title: "Categorie",
    add: "Aggiungi",
    addTitle: "Aggiungi categoria",
    namePlaceholder: "Nome categoria",
    budgetPlaceholder: "Budget (€)",
    fixedLabel: "Spesa fissa",
    delete: "Elimina",
    fixedBadge: "fisso",
    carryForward: "Riporta dal ciclo precedente",
  },
  settings: {
    title: "Impostazioni",
    profile: "Profilo",
    name: "Nome",
    cycleStartDay: "Giorno inizio ciclo",
    defaultSalary: "Stipendio di default (€)",
    save: "Salva",
    currentCycleSalary: "Stipendio del ciclo corrente",
    salary: "Stipendio (€)",
  },
  trends: {
    title: "Andamento — ultimi 6 cicli",
    needMoreData: "Servono almeno due cicli per vedere l'andamento.",
    budgetSeries: "Budget",
    spentSeries: "Speso",
  },
} as const;
