export const copy = {
  app: { title: "Budget", description: "Budget mensile per coppia", shortName: "Budget" },
  auth: {
    loginTitle: "Accedi",
    signupTitle: "Crea account",
    email: "Email",
    password: "Password",
    displayName: "Nome",
    cycleStartDay: "Giorno di inizio del ciclo",
    cycleStartDayHelp: "Il giorno del mese in cui ricevi lo stipendio (1–31).",
    submitLogin: "Accedi",
    submitSignup: "Crea account",
    haveAccount: "Hai già un account?",
    noAccount: "Non hai un account?",
    goLogin: "Accedi",
    goSignup: "Registrati",
    errorGeneric: "Si è verificato un errore. Riprova.",
    signupDisabled: "Registrazione disabilitata.",
    loginFailed: "Email o password errata.",
    submittingLogin: "Accesso…",
    submittingSignup: "Creazione…",
  },
  header: {
    settings: "Impostazioni",
    logout: "Esci",
    cycle: "Ciclo",
    categories: "Categorie",
    import: "Importa",
    menu: "Menù",
    back: "Indietro",
    prevCycle: "Ciclo precedente",
    nextCycle: "Ciclo successivo",
    today: "Oggi",
  },
  fab: { addExpense: "Aggiungi spesa" },
  dashboard: {
    salary: "Stipendio",
    budget: "Budget",
    spent: "Speso",
    remaining: "Rimanente",
    percentSalary: "% stipendio",
    onBudget: (total: string) => `su ${total}`,
    consumed: (pct: string) => `${pct} del budget`,
    pacingTitle: "Andamento ciclo",
    pacingUnder: "In linea ✓",
    pacingOver: "Fuori ritmo ⚠",
    pacingExpense: "Spesa",
    pacingTime: "Tempo",
    categoriesHeading: "Categorie",
    noCategories: "Nessuna categoria.",
    addOne: "Aggiungine una",
    noTransactions: "Nessuna transazione.",
    forecastLabel: "Previsione",
    forecastDeltaOver: (amount: string) => `+ ${amount}`,
    forecastDeltaUnder: (amount: string) => `− ${amount}`,
  },
  expense: {
    newTitle: "Nuova spesa",
    amount: "Importo",
    category: "Categoria",
    date: "Data",
    note: "Nota",
    submit: "Salva",
    cancel: "Annulla",
    noCategory: "Nessuna categoria — creane una prima",
    editTitle: "Modifica spesa",
    update: "Aggiorna",
    delete: "Elimina",
    deleteConfirm: "Eliminare questa spesa?",
  },
  categories: {
    title: "Categorie",
    add: "Aggiungi",
    addTitle: "Aggiungi categoria",
    namePlaceholder: "Nome categoria",
    budgetPlaceholder: "Budget (€)",
    delete: "Elimina",
    edit: "Modifica",
    editTitle: "Modifica categoria",
    save: "Salva",
    cancel: "Annulla",
    carryForward: "Riporta dal ciclo precedente",
  },
  settings: {
    title: "Impostazioni",
    profile: "Profilo",
    name: "Nome",
    cycleStartDay: "Giorno inizio ciclo",
    defaultSalary: "Stipendio di default (€)",
    save: "Salva",
    currentCycleSalary: "Stipendio del ciclo corrente",
    salary: "Stipendio (€)",
  },
  trends: {
    title: "Andamento",
    needMoreData: "Servono almeno due cicli per vedere l'andamento.",
    notEnoughCycles: "Disponibile dal secondo ciclo",
    budgetSeries: "Budget",
    spentSeries: "Speso",
    groupAnnualTitle: "Quest'anno",
    groupAnnualSubtitle: (n: number) => `Ultimi ${n} cicli`,
    groupMonthlyTitle: "Ultimo ciclo",
    groupMonthlySubtitle: "Confronto con il ciclo precedente",
    totalHeading: "Totale",
    moversHeading: "Top movimenti",
    perCategoryHeading: "Per categoria",
    rollupHeading: "Riepilogo",
    tableCategory: "Categoria",
    tableTotal: "Totale",
    tableAverage: "Media",
    tableDelta: "Δ",
    averageLabel: "media",
    headerLink: "Andamento",
  },
  import: {
    title: "Importa da Wallet",
    drop: "Lascia qui il file Wallet",
    dropHint: "Solo CSV · max 5 MB",
    parsing: "Lettura file…",
    parseError: "Formato non riconosciuto",
    subtitle: (n: number, range: string) => `${n} spese da Wallet · ${range}`,
    summaryLabel: "DA IMPORTARE",
    summaryStats: (dup: number, excl: number) => `${dup} duplicati · ${excl} escluse`,
    duplicatedTag: "duplicato",
    unmappedPlaceholder: "Scegli categoria…",
    cyclePrev: (range: string) => `Ciclo precedente · ${range}`,
    cycleCurrent: (range: string) => `Ciclo corrente · ${range}`,
    commitEnabled: (n: number, total: string) => `Importa ${n} spese · ${total}`,
    commitUnmapped: (n: number) => `Risolvi ${n} categorie da assegnare`,
    commitNoneSelected: "Seleziona almeno una spesa",
    commitPending: "Importazione in corso…",
    successTitle: "Spese annotate",
    successSubtitle: (n: number, range: string, total: string) => `${n} voci · ${range} · ${total}`,
    recapHeading: "Riepilogo per categoria",
    recapItem: (count: number) => (count === 1 ? "1 spesa" : `${count} spese`),
    undo: "Annulla importazione",
    undone: "Importazione annullata",
    goDashboard: "Vai alla dashboard",
    nothingNew: "Nessuna nuova spesa",
    drawerCycleHeader: (range: string) => `Ciclo ${range}`,
    createPlaceholder: "Nuova categoria…",
    createButton: "Aggiungi",
    creating: "Creazione…",
    statusDaAssegnare: "Da assegnare",
    errorCategoryMissing: (cat: string, cycle: string) =>
      `Categoria "${cat}" non esiste nel ciclo ${cycle}. Crea la categoria o aggiorna la mappatura.`,
    lastImport: {
      transactionLabel: "Ultima transazione importata",
      uploadLabel: "Ultimo upload",
      exportHint: "Esporta da Wallet dal",
      exportHintSuffix: "in poi",
      emptyState: "Nessun import precedente. Esporta tutto lo storico da Wallet.",
      today: "oggi",
      yesterday: "ieri",
      daysAgo: (n: number) => `${n} giorni fa`,
    },
  },
  mappings: {
    title: "Mappature Wallet",
    empty: "Le mappature appariranno qui dopo il primo import.",
    walletLabel: "Wallet:",
    appLabel: "Categoria:",
    save: "Salva",
    delete: "Elimina",
    settingsLink: "Mappature Wallet",
  },
  search: {
    headerLink: "Ricerca",
    pageTitle: "Ricerca",
    inputPlaceholder: "Cerca in note o categoria…",
    chipDate: "Data",
    chipAmount: "Importo",
    chipCategory: "Categoria",
    counterTemplate: (n: number, amount: string) =>
      `${n} risultati · totale ${amount}`,
    counterZero: "Nessun risultato",
    loadMore: "Carica altri",
    emptyState: "Nessuna spesa nel periodo selezionato",
    rangePresetLast30: "Ultimi 30 giorni",
    rangePresetLast60: "Ultimi 60 giorni",
    rangePresetLast90: "Ultimi 90 giorni",
    rangePresetCurrentCycle: "Ciclo corrente",
    rangePresetCustom: "Personalizzato",
    amountMinLabel: "Importo minimo",
    amountMaxLabel: "Importo massimo",
    applyButton: "Applica",
    clearButton: "Azzera filtri",
    cycleGroupTotal: (range: string, total: string) =>
      `${range} · ${total}`,
  },
  toast: {
    expenseAdded: "Spesa aggiunta",
    expenseUpdated: "Spesa aggiornata",
    expenseDeleted: "Spesa rimossa",
    categorySaved: "Categoria aggiornata",
    categoryDeleted: "Categoria rimossa",
    settingsSaved: "Impostazioni salvate",
    unexpectedError: "Si è verificato un errore. Riprova.",
  },
  errors: {
    invalidInput: "Dati non validi.",
    categoryHasExpenses: "Impossibile eliminare: la categoria ha spese.",
    cycleNotFound: "Ciclo non trovato.",
    noPreviousCycle: "Nessun ciclo precedente.",
    previousCycleEmpty: "Il ciclo precedente non ha categorie.",
    profileNotFound: "Profilo non trovato.",
  },
} as const;
